version: '3'
services: 
    flutter:
        container_name: flutter
        build:
            context: ./ubuntu
            args:
              - FLUTTER_VERSION=${FLUTTER_VERSION}
              - INSTALL_ANDROID=${INSTALL_ANDROID}
        ports:
            - "6080:80"
            - "55555:55555"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        working_dir: ${APP_CODE_PATH_CONTAINER}
        tty: true