name: Flutter Andoroid Build

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'working directory'
        default: './src'
        required: true
        type: string
      flutter_version:
        description: 'flutter version'
        default: '3.0.4'
        required: true
        type: string
      flutter_channel:
        description: 'flutter channel'
        default: 'stable'
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: ${{ inputs.flutter_channel }}
        cache: true
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    # 成果物アップロード
    - name: artifact upload
      uses: actions/upload-artifact@v2.2.0
      with:
        # 保存ファイル名（name.zip）
        name: andoroid
        # 保存するファイル
        path: ./src/build/app/outputs/
        # 保存期間（日）
        retention-days: 1
