name: File existence check

on:
  workflow_call:
    inputs:
      files:
        description: 'file names'
        required: true
        type: string

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ inputs.files }}

      - name: File exists
        if: steps.check_files.outputs.files_exists != 'true'
        run: exit 1
