name: Flutter Test

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'working directory'
        default: './src'
        required: true
        type: string
      flutter_version:
        description: 'flutter version'
        default: '3.0.4'
        required: true
        type: string
      flutter_channel:
        description: 'flutter channel'
        default: 'stable'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: ${{ inputs.flutter_channel }}
        cache: true
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
